name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build with Xcode
      uses: mxcl/xcodebuild@v3
      with:
        xcode: 16.0
        platform: macOS
        arch: arm64
        action: build
        scheme: macSup2Srt
        configuration: release

    - name: Archive
      run: tar cvJf ~/macSup2Srt.tar.xz -C /Users/runner/Library/Developer/Xcode/DerivedData/macSup2Srt-clehdloglthcnmakvqindwnlospi/Build/Products/Release macSup2Srt

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macSup2Srt
        path: ~/macSup2Srt.tar.xz
