name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Select Xcode
      uses: mxcl/xcodebuild@v3
      with:
        xcode: 16.0
        swift: 6.0
        action: none

    - name: Build
      run: xcrun swift build --configuration release --arch arm64 --arch x86_64

    - name: Test
      run: xcrun swift test

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macSubtitleOCR
        path: .build/apple/Products/Release/macSubtitleOCR
