name: Lint
on:
  push:
    paths:
      - '**/*.swift'
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: SwiftFormat
      run: swiftformat --lint . --reporter github-actions-log --disable fileHeader # seems to be broken currently in Actions env
