name: Lint
on:
  push:
    paths:
      - '**/*.swift'
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  lint:
    name: Lint
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout-cone-mode: "blob:none"

    - name: SwiftFormat
      run: swiftformat --lint . --reporter github-actions-log
