name: Nightly Build
on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Select Xcode
      uses: mxcl/xcodebuild@v3
      with:
        xcode: 16.0
        swift: 6.0
        action: none

    - name: Build
      run: |
        xcrun swift build --configuration release --arch arm64 --arch x86_64
        tar -cvJf macSubtitleOCR.tar.xz -C .build/apple/Products/Release macSubtitleOCR

    - name: Publish
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: nightly
        tag_name: nightly
        files: macSubtitleOCR.tar.xz
        prerelease: true
