name: Nightly Build
on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Swift
      uses: swift-actions/setup-swift@v2

    - name: Build
      run: swift build --configuration release

    - name: Publish
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: nightly
        tag_name: nightly
        files: .build/release/macSubtitleOCR
        prerelease: true
