name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: "macos-latest"
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        with:
          gpg_private_key: "${{ secrets.RELEASE_GPG_PRIVATE_KEY }}"
          passphrase: "${{ secrets.RELEASE_GPG_PASSPHRASE }}"

      - name: Install FFmpeg
        run: brew install ffmpeg

      - name: Select Xcode
        uses: mxcl/xcodebuild@v3
        with:
          swift: '6'
          action: none

      - name: Build Standalone
        id: build
        run: |
          TAG=${{ github.ref_name }}
          echo "version=${TAG#v}" >> $GITHUB_ENV
          xcrun swift build --configuration release --arch arm64
          tar -cvJf macSubtitleOCR-${TAG}.tar.xz -C .build/release/ macSubtitleOCR
          gpg --detach-sign --armor macSubtitleOCR-${TAG}.tar.xz
          gpg --verify macSubtitleOCR-${TAG}.tar.xz.asc macSubtitleOCR-${TAG}.tar.xz

      - name: Build with FFmpeg
        run: |
          TAG=${{ github.ref_name }}
          USE_FFMPEG=1 xcrun swift build -Xswiftc -DFFMPEG --configuration release --arch arm64
          tar -cvJf macSubtitleOCR-ffmpeg-${TAG}.tar.xz -C .build/release/ macSubtitleOCR
          gpg --detach-sign --armor macSubtitleOCR-ffmpeg-${TAG}.tar.xz
          gpg --verify macSubtitleOCR-ffmpeg-${TAG}.tar.xz.asc macSubtitleOCR-ffmpeg-${TAG}.tar.xz

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            name: macSubtitleOCR ${{ steps.build.outputs.version }}
            generate_release_notes: true
            make_latest: true
            files: |
              macSubtitleOCR*${{ github.ref_name }}.tar.xz
              macSubtitleOCR*${{ github.ref_name }}.tar.xz.asc
