name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.swift'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.swift'

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install ffmpeg peripheryapp/periphery/periphery

      - name: Select Xcode
        uses: mxcl/xcodebuild@v3
        with:
          swift: '6.0'
          action: none

      - name: Build Tests
        run: xcrun swift test -Xswiftc -DGITHUB_ACTIONS list

      - name: Test FFmpeg Decoder
        timeout-minutes: 7
        run: xcrun swift test --skip-build --filter ffmpegDecoder

      - name: Test Internal Decoder
        timeout-minutes: 7
        run: xcrun swift test --skip-build --filter internalDecoder

      - name: Periphery
        run: periphery scan --skip-build --index-store-path .build/debug/index/store
